{
  try {
    this.extractor.getIntValue(this.person);
    fail("Should have throw an exception");
  }
 catch (  final Exception e) {
  }
}
