{
  KnowledgeBase kbase=loadKnowledgeBase("test_FunctionException.drl");
  StatefulKnowledgeSession ksession=createKnowledgeSession(kbase);
  final Cheese brie=new Cheese("brie",12);
  ksession.insert(brie);
  try {
    ksession.fireAllRules();
    fail("Should throw an Exception from the Function");
  }
 catch (  final Exception e) {
    assertEquals("this should throw an exception",e.getCause().getMessage());
  }
}
