{
  KnowledgeBase kbase=SerializationHelper.serializeObject(loadKnowledgeBase("test_PredicateException.drl"));
  StatefulKnowledgeSession ksession=kbase.newStatefulKnowledgeSession();
  final Cheese brie=new Cheese("brie",12);
  try {
    ksession.insert(brie);
    ksession.fireAllRules();
    fail("Should throw an Exception from the Predicate");
  }
 catch (  final Exception e) {
    Throwable cause=e.getCause();
    if (cause instanceof InvocationTargetException) {
      cause=((InvocationTargetException)cause).getTargetException();
    }
    assertTrue(cause.getMessage().contains("this should throw an exception"));
  }
}
