{
  try {
    this.logout();
  }
 catch (  Exception e) {
    log.error("Finalizer error: " + e.getMessage());
  }
}
