{
  try {
    this.memory.add(this.workingMemory,this.matches0);
    this.memory.add(this.workingMemory,this.matches1);
    Assert.assertEquals("Memory should have size 2",2,this.memory.size());
    Iterator iterator=this.memory.iterator(this.workingMemory,this.tuple0);
    Assert.assertTrue("There should be a next element",iterator.hasNext());
    ObjectMatches om1=(ObjectMatches)iterator.next();
    Assert.assertSame("The first object to return should have been matches1",this.matches1,om1);
    try {
      iterator.remove();
      Assert.fail("Right side memory Iterators are not supposed to support remove()");
    }
 catch (    final UnsupportedOperationException uoe) {
    }
    Assert.assertEquals("Memory should have size 2",2,this.memory.size());
    Assert.assertFalse("There should not be a next element",iterator.hasNext());
    try {
      iterator.next();
      Assert.fail("Iterator is supposed to throw an Exception when there are no more elements");
    }
 catch (    final NoSuchElementException nse) {
    }
    final DummyValueObject obj2=new DummyValueObject(false,"string3",30,"object3");
    final DefaultFactHandle f2=(DefaultFactHandle)this.factory.newFactHandle(obj2);
    final ReteTuple tuple2=new ReteTuple(f2);
    iterator=this.memory.iterator(this.workingMemory,tuple2);
    Assert.assertTrue("There should be a next element",iterator.hasNext());
    final ObjectMatches om0=(ObjectMatches)iterator.next();
    Assert.assertSame("The first object to return should have been matches0",this.matches0,om0);
    om1=(ObjectMatches)iterator.next();
    Assert.assertSame("The second object to return should have been matches1",this.matches1,om1);
    Assert.assertFalse("There should not be a next element",iterator.hasNext());
    try {
      iterator.next();
      Assert.fail("Iterator is supposed to throw an Exception when there are no more elements");
    }
 catch (    final NoSuchElementException nse) {
    }
  }
 catch (  final Exception e) {
    e.printStackTrace();
    Assert.fail("Memory is not supposed to throw any exception during iteration");
  }
}
