{
  KnowledgeBase kbase=loadKnowledgeBase("test_ConsequenceException.drl");
  StatefulKnowledgeSession ksession=kbase.newStatefulKnowledgeSession();
  final Cheese brie=new Cheese("brie",12);
  ksession.insert(brie);
  try {
    ksession.fireAllRules();
    fail("Should throw an Exception from the Consequence");
  }
 catch (  final org.kie.runtime.rule.ConsequenceException e) {
    assertEquals("Throw Consequence Exception",e.getMatch().getRule().getName());
    assertEquals("this should throw an exception",e.getCause().getMessage());
  }
}
