{
  for (  TestOperation testOperation : testOperations) {
    try {
      executeTestOperation(testOperation);
    }
 catch (    Exception e) {
      throw new RuntimeException(createTestFailMessage(testOperations,null,null),e);
    }
  }
}
