{
  try {
    Assert.assertSame(Boolean.TRUE,this.extractor.getValue(null,this.bean));
  }
 catch (  final Exception e) {
    fail("Should not throw an exception");
  }
}
