{
  try {
    this.memory.add(this.workingMemory,tuple0);
    this.memory.add(this.workingMemory,tuple1);
    Assert.assertEquals("Memory should have size 2",2,this.memory.size());
    Iterator iterator=this.memory.iterator(workingMemory,f0);
    Assert.assertTrue("There should be a next element",iterator.hasNext());
    ReteTuple t0=(ReteTuple)iterator.next();
    Assert.assertSame("The first object to return should have been tuple0",tuple0,t0);
    iterator.remove();
    Assert.assertEquals("Memory should have size 1",1,this.memory.size());
    Assert.assertTrue("There should be a next element",iterator.hasNext());
    ReteTuple t1=(ReteTuple)iterator.next();
    Assert.assertSame("The second object to return should have been tuple1",tuple1,t1);
    Assert.assertFalse("There should not be a next element",iterator.hasNext());
    try {
      iterator.next();
      Assert.fail("Iterator is supposed to throw an Exception when there are no more elements");
    }
 catch (    NoSuchElementException nse) {
    }
  }
 catch (  Exception e) {
    Assert.fail("Memory is not supposed to throw any exception during iteration");
  }
}
